<?xml version="1.0" encoding="utf-8"?><Database Name="InventoryManagement" Class="InventoryDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\InventoryManagement.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="InventoryManagement.Properties.Settings" SettingsPropertyName="InventoryManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MRP" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Inventory_Transaction" Member="Transactions" ThisKey="Id" OtherKey="InventoryItem" Type="Transaction" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InventoryItem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SellingPrice" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SaleDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Inventory_Transaction" Member="Inventory" ThisKey="InventoryItem" OtherKey="Id" Type="Inventory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>